import { test, expect } from '@playwright/test';

test.describe('Critical Path: Intake to Dashboard', () => {

    test('should guide user from landing page to dashboard', async ({ page }) => {
        test.setTimeout(120000); // Increase timeout to 120s for full LLM generation flow

        // Debug Logging
        page.on('console', msg => console.log(`[BROWSER] ${msg.text()}`));
        page.on('pageerror', err => console.error(`[BROWSER ERROR] ${err.message}`));

        // Mock Supabase Edge Function to speed up test and avoid API costs
        await page.route('**/functions/v1/generate-plan-proxy', async route => {
            console.log('[TEST] Mocking generate-plan-proxy response');
            const json = {
                user_name: 'Testhans',
                plan_summary: 'Generated by E2E Mock',
                start_date: new Date().toISOString().split('T')[0],
                generated_at: new Date().toISOString(),
                primary_focus_pillars: ['sleep', 'stress'],
                meta: {
                    input: { submitted_at: new Date().toISOString() }
                },
                days: Array.from({ length: 30 }, (_, i) => ({
                    day: i + 1,
                    theme: `Mock Day ${i + 1}`,
                    tasks: [
                        { id: `d${i + 1}_t1`, task: 'Morning Water', pillar: 'nutrition', time_minutes: 1, when: 'morning' },
                        { id: `d${i + 1}_t2`, task: 'Breathing', pillar: 'stress', time_minutes: 5, when: 'evening' }
                    ],
                    total_time_minutes: 6
                }))
            };
            await route.fulfill({ json });
        });

        // 1. Visit Landing Page
        await page.goto('/');
        await expect(page).toHaveTitle(/ExtensioVitae/);

        // 3. Complete Intake
        // Direct navigation to intake to ensure stability
        await page.goto('/intake');
        await expect(page.url()).toContain('/intake');

        // --- Step 0: Basics ---
        // Name
        const nameInput = page.getByPlaceholder(/First name|Name/i);
        await nameInput.fill('Testhans');

        // Age
        const ageInput = page.getByPlaceholder(/Age/i);
        await ageInput.fill('35');

        // Sex (Option Button)
        await page.getByRole('button', { name: /^Male$/i }).click();

        // Next
        await page.getByRole('button', { name: /Next|Weiter|Continue/i }).click();

        // --- Step 1: Status ---
        // Sleep
        await page.getByRole('button', { name: /7.5 - 8 hours|7.5-8/i }).click();

        // Training
        await page.getByRole('button', { name: /3-4 times/i }).click();

        // Diet (Multiselect - pick one)
        await page.getByRole('button', { name: /Mostly Whole Foods/i }).click();

        // Wait a bit for transitions
        await page.waitForTimeout(300);

        // Next
        await page.getByRole('button', { name: /Next|Weiter|Continue/i }).click();

        // --- Step 2: Goals ---
        // Step 2: Goals
        // Primary Goal
        await page.getByRole('button', { name: 'More Energy' }).click();

        // Consent Checkbox
        await page.getByRole('checkbox').check();

        // Wait a bit
        await page.waitForTimeout(300);

        // Final Submit: "Generate Blueprint"
        // Try searching for the text specifically
        const submitBtn = page.getByRole('button', { name: /Generate|Erstellen/i });
        await submitBtn.click();

        // 4. Generating Page -> Dashboard
        // Might redirect to /generating then /dashboard/d/...
        // Allow up to 10s for generation
        // Wait for generation page
        await expect(page).toHaveURL(/\/generating/, { timeout: 15000 });

        // 4. Confirm Plan (Review Modal)
        const confirmBtn = page.getByRole('button', { name: /Los geht's|Start/i });
        // Generation + Animation can take time
        await expect(confirmBtn).toBeVisible({ timeout: 60000 });
        await confirmBtn.click();

        // 5. Verify Redirect
        // App now redirects to Auth for new users, or Dashboard if guest access active
        await expect(page).toHaveURL(/\/dashboard|\/auth/, { timeout: 15000 });

        const url = page.url();
        console.log(`[TEST] Final URL: ${url}`);

        if (url.includes('/dashboard')) {
            await expect(page.locator('[data-tour="daily-progress"]')).toBeVisible({ timeout: 20000 });
        } else if (url.includes('/auth')) {
            // If redirected to auth, we consider the critical path "intake -> plan generation" complete
            await expect(page.getByRole('heading', { name: /Sign|Account|Anmelden/i })).toBeVisible();
        }
    });

});
